name: prediksihargabitcoin
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy=1.23.5
  - pandas=1.5.3
  - scikit-learn=1.0.2
  - joblib=1.1.0
  - matplotlib=3.7.1
  - h5py=3.8.0
  - protobuf=3.20.3
  - pip:
      - streamlit==1.26.0
